extends: ["spectral:oas"]
rules:
  operation-operationId: error
  path-params: off
  oas3-api-servers: off
  info-contact: off
  info-description: off
  operation-description: off
  operation-tag-defined: off
  oas3-unused-component: off
