#!/bin/bash
set -e

# ─── Timezone ─────────────────────────────────────────────────────────────────
if [ -n "${TZ}" ] && [ -f "/usr/share/zoneinfo/${TZ}" ]; then
    ln -snf "/usr/share/zoneinfo/${TZ}" /etc/localtime
    echo "${TZ}" > /etc/timezone
    echo "Timezone set to ${TZ}"
fi

# ─── PUID / PGID ─────────────────────────────────────────────────────────────
PUID="${PUID:-1654}"
PGID="${PGID:-1654}"

if [ "$(id -g app)" != "${PGID}" ]; then
    groupmod -g "${PGID}" app
fi
if [ "$(id -u app)" != "${PUID}" ]; then
    usermod -u "${PUID}" -o app
fi

echo "Running as uid=$(id -u app) gid=$(id -g app)"

chown -R app:app /app

# /data may contain a read-only bind mount — staging the embedding model from a
# connected machine is a supported air-gapped pattern (see docs/deployment.md). chown
# still fixes everything writable; failing the boot over the parts it cannot touch
# would turn that into a restart loop.
if ! chown -R app:app /data 2>/dev/null; then
    echo "Note: parts of /data are read-only and were left as-is"
fi

# ─── Secrets bridge ──────────────────────────────────────────────────────────
# Read file-based secrets (generated by the init container) and export as
# environment variables that the .NET app expects.

if [ ! -f /secrets/pg_password ]; then
    echo "ERROR: /secrets/pg_password not found. Is the secrets volume mounted?" >&2
    exit 1
fi
if [ ! -f /secrets/jwt_key ]; then
    echo "ERROR: /secrets/jwt_key not found. Is the secrets volume mounted?" >&2
    exit 1
fi
if [ ! -f /secrets/admin_password ]; then
    echo "ERROR: /secrets/admin_password not found. Is the secrets volume mounted?" >&2
    exit 1
fi

export POSTGRES_PASSWORD
POSTGRES_PASSWORD="$(cat /secrets/pg_password)"
export Jwt__Key
Jwt__Key="$(cat /secrets/jwt_key)"
export AdminSeed__Password
AdminSeed__Password="$(cat /secrets/admin_password)"

echo "Secrets loaded from /secrets volume"

# ─── Run ──────────────────────────────────────────────────────────────────────
echo "Running database migrations..."
gosu app dotnet tools/DbMigrator/DbMigrator.dll

echo "Seeding database..."
gosu app dotnet tools/DbSeeder/DbSeeder.dll

if [ ! -f /data/.seeded ]; then
    echo ""
    echo "========================================"
    echo "  Admin credentials (first launch)"
    echo "  Email:    ${AdminSeed__Email}"
    echo "  Password: ${AdminSeed__Password}"
    echo "  Change this password immediately."
    echo "========================================"
    echo ""
    gosu app touch /data/.seeded
fi

echo "Starting API..."
exec gosu app dotnet API.dll
