// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260406003035_AddSoftDeleteToYnabSyncRecords")]
    partial class AddSoftDeleteToYnabSyncRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Entities.ApiKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("BypassRateLimit")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Infrastructure.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("MustResetPassword")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.Audit.AuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("ChangedByApiKeyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("ChangedByApiKeyId");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Infrastructure.Entities.Audit.AuthAuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApiKeyId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress");

                    b.HasIndex("Timestamp");

                    b.HasIndex("EventType", "Timestamp");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("AuthAuditLogs");
                });

            modelBuilder.Entity("Infrastructure.Entities.Core.AccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Infrastructure.Entities.Core.AdjustmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AmountCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CascadeDeletedByParentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("DeletedByApiKeyId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId");

                    b.ToTable("Adjustments");
                });

            modelBuilder.Entity("Infrastructure.Entities.Core.CategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CascadeDeletedByParentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("DeletedByApiKeyId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("83a7f4ea-f771-40b3-850f-35b90a3bd05e"),
                            Description = "Food and household supplies",
                            IsActive = true,
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = new Guid("e37ce004-56ea-4a33-8983-55a9552d05be"),
                            Description = "Restaurants, takeout, and delivery",
                            IsActive = true,
                            Name = "Dining"
                        },
                        new
                        {
                            Id = new Guid("3a131ca1-3300-4cde-b7ee-24704934feea"),
                            Description = "Gas, transit, parking, and rideshare",
                            IsActive = true,
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = new Guid("92eae007-7d82-492c-9370-ff64873cc63a"),
                            Description = "Clothing, electronics, and general retail",
                            IsActive = true,
                            Name = "Shopping"
                        },
                        new
                        {
                            Id = new Guid("705da6c5-6fb6-4b3c-aef1-f42e5136a499"),
                            Description = "Electric, water, internet, and phone",
                            IsActive = true,
                            Name = "Utilities"
                        },
                        new
                        {
                            Id = new Guid("f0e7a123-9b56-4d3a-8c1e-2a5b7d9f4e6c"),
                            Description = "Default category for items without a valid category",
                            IsActive = true,
                            Name = "Uncategorized"
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Core.ItemEmbeddingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(384)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId")
                        .IsUnique();

                    b.ToTable("ItemEmbeddings", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.Core.ItemTemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CascadeDeletedByParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultCategory")
                        .HasColumnType("text");

                    b.Property<string>("DefaultItemCode")
                        .HasColumnType("text");

                    b.Property<string>("DefaultPricingMode")
                        .HasColumnType("text");

                    b.Property<string>("DefaultSubcategory")
                        .HasColumnType("text");

                    b.Property<decimal?>("DefaultUnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DefaultUnitPriceCurrency")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("DeletedByApiKeyId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("ItemTemplates", null, t =>
                        {
                            t.HasCheckConstraint("CK_ItemTemplates_Money_Consistency", "((\"DefaultUnitPrice\" IS NULL AND \"DefaultUnitPriceCurrency\" IS NULL) OR (\"DefaultUnitPrice\" IS NOT NULL AND \"DefaultUnitPriceCurrency\" IS NOT NULL))");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb05ed31-92a0-4c3d-bdbe-b9bd05183f38"),
                            DefaultCategory = "Groceries",
                            DefaultItemCode = "MILK-GAL",
                            DefaultPricingMode = "quantity",
                            DefaultSubcategory = "Dairy",
                            DefaultUnitPrice = 4.99m,
                            DefaultUnitPriceCurrency = "USD",
                            Name = "Gallon of Milk"
                        },
                        new
                        {
                            Id = new Guid("33255f68-44df-4813-ad55-92260303c0ce"),
                            DefaultCategory = "Groceries",
                            DefaultItemCode = "BREAD",
                            DefaultPricingMode = "quantity",
                            DefaultSubcategory = "Bakery",
                            DefaultUnitPrice = 3.49m,
                            DefaultUnitPriceCurrency = "USD",
                            Name = "Loaf of Bread"
                        },
                        new
                        {
                            Id = new Guid("3d11bbb7-ee69-4701-a45c-58bfc6458158"),
                            DefaultCategory = "Dining",
                            DefaultItemCode = "COFFEE-M",
                            DefaultPricingMode = "flat",
                            DefaultSubcategory = "Coffee Shop",
                            DefaultUnitPrice = 4.50m,
                            DefaultUnitPriceCurrency = "USD",
                            Name = "Coffee (Medium)"
                        },
                        new
                        {
                            Id = new Guid("a2de7840-ef72-42d5-b90f-9c25eb63f502"),
                            DefaultCategory = "Transportation",
                            DefaultItemCode = "GAS-REG",
                            DefaultPricingMode = "quantity",
                            DefaultSubcategory = "Gas",
                            Name = "Regular Unleaded Gas"
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Core.ReceiptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CascadeDeletedByParentId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("DeletedByApiKeyId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalImagePath")
                        .HasMaxLength(1024)
                        .HasColumnType("text");

                    b.Property<string>("ProcessedImagePath")
                        .HasMaxLength(1024)
                        .HasColumnType("text");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TaxAmountCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("Infrastructure.Entities.Core.ReceiptItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CascadeDeletedByParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("DeletedByApiKeyId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PricingMode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReceiptItemCode")
                        .HasColumnType("text");

                    b.Property<string>("Subcategory")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TotalAmountCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitPriceCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId");

                    b.ToTable("ReceiptItems");
                });

            modelBuilder.Entity("Infrastructure.Entities.Core.SubcategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CascadeDeletedByParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("DeletedByApiKeyId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Name")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("Subcategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bdc5740a-352e-44a9-bd1d-a85f5b0cb833"),
                            CategoryId = new Guid("83a7f4ea-f771-40b3-850f-35b90a3bd05e"),
                            Description = "Fruits and vegetables",
                            IsActive = true,
                            Name = "Produce"
                        },
                        new
                        {
                            Id = new Guid("d8052b39-045a-4c1f-b0a5-3b94920fe010"),
                            CategoryId = new Guid("83a7f4ea-f771-40b3-850f-35b90a3bd05e"),
                            Description = "Milk, cheese, yogurt",
                            IsActive = true,
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = new Guid("7bb01875-3807-44a2-b8fb-3459a514d81f"),
                            CategoryId = new Guid("83a7f4ea-f771-40b3-850f-35b90a3bd05e"),
                            IsActive = true,
                            Name = "Meat & Seafood"
                        },
                        new
                        {
                            Id = new Guid("2e5bef54-3b06-4d8d-8f53-7f94e8d88e99"),
                            CategoryId = new Guid("83a7f4ea-f771-40b3-850f-35b90a3bd05e"),
                            IsActive = true,
                            Name = "Bakery"
                        },
                        new
                        {
                            Id = new Guid("2ba877ec-9581-4927-aaea-729a778fb8ae"),
                            CategoryId = new Guid("e37ce004-56ea-4a33-8983-55a9552d05be"),
                            IsActive = true,
                            Name = "Fast Food"
                        },
                        new
                        {
                            Id = new Guid("af940cc4-9838-46ac-8c30-3573d876ae47"),
                            CategoryId = new Guid("e37ce004-56ea-4a33-8983-55a9552d05be"),
                            IsActive = true,
                            Name = "Sit-Down Restaurant"
                        },
                        new
                        {
                            Id = new Guid("9c90a29d-546c-4ab8-a5f7-4168b675cda8"),
                            CategoryId = new Guid("e37ce004-56ea-4a33-8983-55a9552d05be"),
                            IsActive = true,
                            Name = "Coffee Shop"
                        },
                        new
                        {
                            Id = new Guid("8fd8809c-7081-4997-925c-49c0a244a4e4"),
                            CategoryId = new Guid("3a131ca1-3300-4cde-b7ee-24704934feea"),
                            IsActive = true,
                            Name = "Gas"
                        },
                        new
                        {
                            Id = new Guid("079d5267-8091-460b-86d4-7b2565b8bb25"),
                            CategoryId = new Guid("3a131ca1-3300-4cde-b7ee-24704934feea"),
                            IsActive = true,
                            Name = "Parking"
                        },
                        new
                        {
                            Id = new Guid("ad045a79-d5a1-404e-b7a8-c475680681f1"),
                            CategoryId = new Guid("92eae007-7d82-492c-9370-ff64873cc63a"),
                            IsActive = true,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("d00f80ca-5e7a-44f8-bf97-b44fccb430b1"),
                            CategoryId = new Guid("92eae007-7d82-492c-9370-ff64873cc63a"),
                            IsActive = true,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("f7c4d461-ed9f-421c-94d3-32e9a55d6bb0"),
                            CategoryId = new Guid("705da6c5-6fb6-4b3c-aef1-f42e5136a499"),
                            IsActive = true,
                            Name = "Electric"
                        },
                        new
                        {
                            Id = new Guid("c9205933-8cc6-4dfc-b08f-46ba221036fa"),
                            CategoryId = new Guid("705da6c5-6fb6-4b3c-aef1-f42e5136a499"),
                            IsActive = true,
                            Name = "Internet"
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Core.TransactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AmountCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CascadeDeletedByParentId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("DeletedByApiKeyId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Infrastructure.Entities.Core.YnabAccountMappingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("ReceiptsAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("YnabAccountId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("YnabAccountName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("text");

                    b.Property<string>("YnabBudgetId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptsAccountId")
                        .IsUnique();

                    b.ToTable("YnabAccountMappings");
                });

            modelBuilder.Entity("Infrastructure.Entities.Core.YnabCategoryMappingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ReceiptsCategory")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("YnabBudgetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text");

                    b.Property<string>("YnabCategoryGroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text");

                    b.Property<string>("YnabCategoryId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text");

                    b.Property<string>("YnabCategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptsCategory")
                        .IsUnique();

                    b.ToTable("YnabCategoryMappings");
                });

            modelBuilder.Entity("Infrastructure.Entities.Core.YnabSelectedBudgetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BudgetId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.ToTable("YnabSelectedBudgets");
                });

            modelBuilder.Entity("Infrastructure.Entities.Core.YnabSyncRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CascadeDeletedByParentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("DeletedByApiKeyId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("text");

                    b.Property<Guid>("LocalTransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SyncType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SyncedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("YnabAccountId")
                        .HasColumnType("text");

                    b.Property<string>("YnabBudgetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YnabTransactionId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocalTransactionId", "SyncType")
                        .IsUnique();

                    b.ToTable("YnabSyncRecords");
                });

            modelBuilder.Entity("Infrastructure.Entities.SeedHistoryEntry", b =>
                {
                    b.Property<string>("SeedId")
                        .HasMaxLength(150)
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("SeedId");

                    b.ToTable("__SeedHistory", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.ApiKeyEntity", b =>
                {
                    b.HasOne("Infrastructure.Entities.ApplicationUser", "User")
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Entities.Core.AdjustmentEntity", b =>
                {
                    b.HasOne("Infrastructure.Entities.Core.ReceiptEntity", "Receipt")
                        .WithMany()
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("Infrastructure.Entities.Core.ReceiptItemEntity", b =>
                {
                    b.HasOne("Infrastructure.Entities.Core.ReceiptEntity", "Receipt")
                        .WithMany()
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("Infrastructure.Entities.Core.SubcategoryEntity", b =>
                {
                    b.HasOne("Infrastructure.Entities.Core.CategoryEntity", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Infrastructure.Entities.Core.TransactionEntity", b =>
                {
                    b.HasOne("Infrastructure.Entities.Core.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Entities.Core.ReceiptEntity", "Receipt")
                        .WithMany()
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("Infrastructure.Entities.Core.YnabAccountMappingEntity", b =>
                {
                    b.HasOne("Infrastructure.Entities.Core.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("ReceiptsAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Infrastructure.Entities.Core.YnabSyncRecordEntity", b =>
                {
                    b.HasOne("Infrastructure.Entities.Core.TransactionEntity", "Transaction")
                        .WithMany()
                        .HasForeignKey("LocalTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.ApplicationUser", b =>
                {
                    b.Navigation("ApiKeys");
                });

            modelBuilder.Entity("Infrastructure.Entities.Core.CategoryEntity", b =>
                {
                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
