using System.Reflection;
using FluentAssertions;
using Infrastructure.Services;
using Microsoft.Extensions.Logging;
using Moq;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;

namespace Infrastructure.Tests.Services;

/// <summary>
/// Fixture-based integration tests for <see cref="PdfConversionService"/> that
/// exercise color spaces and filters PdfPig.Writer.PdfDocumentBuilder cannot
/// synthesize (RECEIPTS-651).
///
/// <para>
/// RECEIPTS-629 deferred coverage for CMYK and JBIG2 because PdfDocumentBuilder
/// cannot emit either encoding. This test class loads real binary PDFs from
/// <c>tests/Infrastructure.Tests/Fixtures/Pdf/</c> (committed to the repo) and
/// verifies that <c>PdfConversionService.ConvertAsync</c> rasterizes the first
/// page successfully via PDFium.
/// </para>
///
/// <para>
/// The fixtures are kept tiny (&lt; 5 KB each) and are regenerated by
/// <c>tests/Infrastructure.Tests/Fixtures/Pdf/_generate_fixtures.py</c>. They are
/// embedded as <c>EmbeddedResource</c> entries in <c>Infrastructure.Tests.csproj</c>
/// so the runner can load them regardless of the working directory.
/// </para>
///
/// <para>
/// These tests invoke PDFium via PDFtoImage and so take a few hundred ms each.
/// They are not slow enough to warrant the <c>Slow</c> trait, but they also do
/// not need the <c>Integration</c> trait — they have no external dependencies.
/// </para>
/// </summary>
public class PdfConversionServiceFixtureTests
{
	private readonly PdfConversionService _service;

	public PdfConversionServiceFixtureTests()
	{
		Mock<ILogger<PdfConversionService>> mockLogger = new();
		_service = new PdfConversionService(mockLogger.Object);
	}

	[Fact]
	public async Task ConvertAsync_CmykPdfFixture_RasterizesFirstPage()
	{
		// Arrange — CMYK is a high-priority gap from RECEIPTS-629. Print scans
		// from many POS systems use DeviceCMYK rather than DeviceRGB. PDFium
		// must convert CMYK to RGB transparently when rasterizing.
		byte[] pdfBytes = LoadFixture("cmyk-receipt.pdf");

		// Act
		byte[] firstPagePng = await _service.ConvertAsync(pdfBytes, CancellationToken.None);

		// Assert
		AssertValidPng(firstPagePng, minWidth: 100, minHeight: 100);
	}

	[Fact]
	public async Task ConvertAsync_IndexedColorPdfFixture_RasterizesFirstPage()
	{
		// Arrange — palette / indexed-color images are common in scanner-app
		// exports that compress to small palettes. PDFium must dereference the
		// /Indexed color space and look up palette entries when rasterizing.
		byte[] pdfBytes = LoadFixture("indexed-receipt.pdf");

		// Act
		byte[] firstPagePng = await _service.ConvertAsync(pdfBytes, CancellationToken.None);

		// Assert
		AssertValidPng(firstPagePng, minWidth: 100, minHeight: 100);
	}

	[Fact]
	public async Task ConvertAsync_CalRgbColorSpacePdfFixture_RasterizesFirstPage()
	{
		// Arrange — CalRGB is a CIE-based calibrated RGB color space (common in
		// PDFs from older scanner / preflight tools). PDFium must accept the
		// calibration profile and produce sensible RGB output.
		byte[] pdfBytes = LoadFixture("calrgb-receipt.pdf");

		// Act
		byte[] firstPagePng = await _service.ConvertAsync(pdfBytes, CancellationToken.None);

		// Assert
		AssertValidPng(firstPagePng, minWidth: 100, minHeight: 100);
	}

	[Fact]
	public async Task ConvertAsync_LabColorSpacePdfFixture_RasterizesFirstPage()
	{
		// Arrange — Lab is another CIE-based non-DeviceRGB color space. Together
		// with CalRGB, it covers PDFium's two main calibrated-color paths.
		byte[] pdfBytes = LoadFixture("lab-receipt.pdf");

		// Act
		byte[] firstPagePng = await _service.ConvertAsync(pdfBytes, CancellationToken.None);

		// Assert
		AssertValidPng(firstPagePng, minWidth: 100, minHeight: 100);
	}

	[Fact(Skip = "JBIG2 fixture requires the external `jbig2enc` binary which is not " +
		"available on most developer machines. PdfPig.Writer.PdfDocumentBuilder cannot " +
		"emit JBIG2-encoded streams either. PDFium does support /JBIG2Decode in production, " +
		"so this test is documented as a gap. Source a real JBIG2 PDF (e.g. from a Xerox " +
		"WorkCentre scan) and add it as `jbig2-receipt.pdf` to enable. See RECEIPTS-651.")]
	public Task ConvertAsync_Jbig2EncodedPdfFixture_RasterizesFirstPage()
	{
		// Intentionally empty — see Skip reason above.
		return Task.CompletedTask;
	}

	/// <summary>
	/// Loads a fixture PDF from the assembly's embedded resources. Embedded
	/// resources are namespace-qualified by default
	/// (<c>Infrastructure.Tests.Fixtures.Pdf.&lt;name&gt;</c>) when they live under
	/// the project root. This avoids depending on the runner's working directory.
	/// </summary>
	private static byte[] LoadFixture(string fileName)
	{
		Assembly assembly = typeof(PdfConversionServiceFixtureTests).Assembly;
		string resourceName = $"Infrastructure.Tests.Fixtures.Pdf.{fileName}";

		using Stream? stream = assembly.GetManifestResourceStream(resourceName)
			?? throw new InvalidOperationException(
				$"Embedded resource '{resourceName}' not found. Available resources: " +
				string.Join(", ", assembly.GetManifestResourceNames()));

		using MemoryStream ms = new();
		stream.CopyTo(ms);
		return ms.ToArray();
	}

	private static void AssertValidPng(byte[] png, int minWidth, int minHeight)
	{
		png.Should().NotBeNullOrEmpty();
		png.Length.Should().BeGreaterThan(8);
		// PNG magic: 89 50 4E 47 0D 0A 1A 0A
		png[0].Should().Be(0x89);
		png[1].Should().Be(0x50);
		png[2].Should().Be(0x4E);
		png[3].Should().Be(0x47);

		using Image<Rgba32> img = Image.Load<Rgba32>(png);
		img.Width.Should().BeGreaterThanOrEqualTo(minWidth);
		img.Height.Should().BeGreaterThanOrEqualTo(minHeight);
	}
}
