#!/usr/bin/env python3
"""Add cross-reference links between docs/issues/ markdown files.

For each issue file:
  - Builds a map of MGG-NNN -> filename
  - Replaces bare MGG-NNN references in the body (not frontmatter, not already
    linked, not the file's own identifier) with [MGG-NNN](./filename.md)
  - Generates an index organized by phase/milestone
"""

import re
import sys
from collections import defaultdict
from pathlib import Path

ISSUES_DIR = Path(__file__).resolve().parent.parent / "docs" / "issues"


def build_id_to_file_map(issues_dir: Path) -> dict[int, Path]:
    """Map issue sequence number -> file path."""
    mapping: dict[int, Path] = {}
    for f in issues_dir.glob("mgg-*.md"):
        m = re.match(r"mgg-(\d+)", f.stem)
        if m:
            mapping[int(m.group(1))] = f
    return mapping


def parse_frontmatter(text: str) -> tuple[str, str]:
    """Split file into frontmatter and body. Returns (frontmatter, body)."""
    if text.startswith("---"):
        end = text.find("---", 3)
        if end != -1:
            fm_end = end + 3
            return text[:fm_end], text[fm_end:]
    return "", text


def get_own_id(frontmatter: str) -> int | None:
    """Extract the issue's own sequence number from frontmatter identifier field."""
    m = re.search(r"^identifier:\s*MGG-(\d+)", frontmatter, re.MULTILINE)
    if m:
        return int(m.group(1))
    return None


def get_milestone(frontmatter: str) -> str:
    """Extract milestone from frontmatter."""
    m = re.search(r'^milestone:\s*"?([^"\n]+)"?', frontmatter, re.MULTILINE)
    if m:
        return m.group(1).strip()
    return "Uncategorized"


def get_title(frontmatter: str) -> str:
    """Extract title from frontmatter."""
    m = re.search(r"^title:\s*(.+)$", frontmatter, re.MULTILINE)
    if m:
        return m.group(1).strip().strip('"')
    return ""


def get_status(frontmatter: str) -> str:
    """Extract status from frontmatter."""
    m = re.search(r"^status:\s*(\S+)", frontmatter, re.MULTILINE)
    if m:
        return m.group(1).strip()
    return ""


def get_labels(frontmatter: str) -> list[str]:
    """Extract labels list from frontmatter."""
    labels = []
    in_labels = False
    for line in frontmatter.split("\n"):
        if re.match(r"^labels:", line):
            in_labels = True
            continue
        if in_labels:
            m = re.match(r"^\s+-\s+(.+)", line)
            if m:
                labels.append(m.group(1).strip())
            else:
                break
    return labels


def linkify_body(
    body: str,
    own_id: int | None,
    id_to_file: dict[int, Path],
    issues_dir: Path,
) -> str:
    """Replace bare MGG-NNN references with markdown links."""

    def replace_match(m: re.Match) -> str:
        full = m.group(0)
        num = int(m.group(1))

        # Don't link to self
        if num == own_id:
            return full

        # Don't link if no file exists
        if num not in id_to_file:
            return full

        filename = id_to_file[num].name
        return f"[{full}](./{filename})"

    # Match MGG-NNN that is NOT already inside a markdown link
    # Negative lookbehind for [ (already part of link text) or ( (already a link target)
    # Also avoid matching inside frontmatter identifier fields
    pattern = r"(?<!\[)(?<!\()MGG-(\d+)(?!\])"
    return re.sub(pattern, replace_match, body)


def generate_index(
    id_to_file: dict[int, Path],
    issues_dir: Path,
) -> str:
    """Generate a phase-organized index of all issues."""
    phases: dict[str, list[tuple[int, str, str, list[str]]]] = defaultdict(list)

    for num, filepath in sorted(id_to_file.items()):
        text = filepath.read_text(encoding="utf-8")
        fm, _ = parse_frontmatter(text)
        milestone = get_milestone(fm)
        title = get_title(fm)
        labels = get_labels(fm)
        phases[milestone].append((num, title, filepath.name, labels))

    # Sort phases by extracting phase number
    def phase_sort_key(name: str) -> tuple[int, str]:
        m = re.search(r"Phase\s+(\d+)", name)
        if m:
            return (int(m.group(1)), name)
        return (999, name)

    lines = [
        "# Issue Archive",
        "",
        "Archived Linear issue specifications, organized by milestone/phase.",
        "",
        f"**{len(id_to_file)} issues** across {len(phases)} milestones.",
        "",
    ]

    for phase_name in sorted(phases.keys(), key=phase_sort_key):
        issues = phases[phase_name]
        lines.append(f"## {phase_name}")
        lines.append("")
        lines.append("| Issue | Title | Labels |")
        lines.append("|-------|-------|--------|")
        for num, title, filename, labels in sorted(issues):
            issue_id = f"MGG-{num}"
            label_str = ", ".join(f"`{l}`" for l in labels)
            lines.append(f"| [{issue_id}](./{filename}) | {title} | {label_str} |")
        lines.append("")

    lines.append(
        "*This index is auto-generated by `scripts/link-issue-docs.py`.*\n"
    )
    return "\n".join(lines)


def main() -> int:
    if not ISSUES_DIR.exists():
        print(f"ERROR: {ISSUES_DIR} does not exist", file=sys.stderr)
        return 1

    id_to_file = build_id_to_file_map(ISSUES_DIR)
    print(f"Found {len(id_to_file)} issue files")

    modified = 0
    links_added = 0

    for num, filepath in sorted(id_to_file.items()):
        text = filepath.read_text(encoding="utf-8")
        fm, body = parse_frontmatter(text)
        own_id = get_own_id(fm)

        new_body = linkify_body(body, own_id, id_to_file, ISSUES_DIR)

        if new_body != body:
            filepath.write_text(fm + new_body, encoding="utf-8")
            added = new_body.count("](./mgg-") - body.count("](./mgg-")
            links_added += added
            modified += 1

    print(f"Modified {modified} files, added {links_added} links")

    # Generate index
    index_content = generate_index(id_to_file, ISSUES_DIR)
    index_path = ISSUES_DIR / "README.md"
    index_path.write_text(index_content, encoding="utf-8")
    print(f"Generated index at {index_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
